axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.3
scale_linear_turbo: 1.0

axis_angular: 3  # Right thumb stick horizontal
scale_angular: 1.0

enable_button: 4  # Left trigger button
enable_turbo_button: 5  # Right trigger button
